# Generated by Django 5.2.7 on 2025-10-21 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('borrowingid', models.AutoField(primary_key=True, serialize=False)),
                ('borrowdate', models.DateField(default=django.utils.timezone.now)),
                ('duedate', models.DateField()),
                ('returndate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'borrowing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('comicid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('releasedate', models.DateField()),
                ('availablenumber', models.IntegerField()),
            ],
            options={
                'db_table': 'comic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComicAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'comicauthor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreid', models.AutoField(primary_key=True, serialize=False)),
                ('genrename', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisherid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('foundedyear', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'publisher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('readerid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('joindate', models.DateField(default=django.utils.timezone.now)),
                ('isblocked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('reviewdate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
